# Default opacity of active windows.
active-opacity = 1.0;

# Default opacity of inactive windows.
inactive-opacity = 1.0;

# Opacity of window titlebars and borders.
frame-opacity = 1.0;  # Ensure window borders are fully opaque

# Application-specific settings; these override the default `active-opacity`
# Full opacity for Librewolf, ensuring no opacity for window or borders
opacity-rule = [
    "95:class_g = 'Alacritty' && focused",
    "80:class_g = 'Alacritty' && !focused",
    "99:class_g = 'LibreWolf' && focused",
    "80:class_g = 'LibreWolf' && !focused"
];
